### ISSUE TITLE
Initial version of the component

### ISSUE THREAD

**Issue by pleku** [vaadin/vaadin-context-menu-flow#1]
- V10 compatible
- Initial feature set
  - Grid specific features and API excluded for now
- add validation build, all the setup for that (reviewable, sonar ...)
- add release build
- release version 1.0.0.alpha1 (doesn't go to V10 platform)

**Comment by pekam** [comment]
[EDIT: This comment is not important anymore]

I'm moving this back to the backlog as I'm working with IE11 test fixes. I have a branch with the initialized project and `ContextMenu` working with component renderers similar to `Dialog`: https://github.com/vaadin/vaadin-context-menu-flow/tree/initial-implementation

We have a couple of design decisions that we need to make:
1. The web component works in a way that it's the parent of its target content (the elements that you can right-click to open the context-menu). The contents of the context-menu are defined in a template inside the component. Take a look at the demos: https://cdn.vaadin.com/vaadin-context-menu/4.1.0-alpha1/demo/#context-menu-basic-demos
So we have a problem: To follow the DOM structure, `add()` and `remove()` methods should add and remove targets of the context-menu, not its contents. But it feels more logical to add and remove components in the context-menu itself (which is implemented in my branch with component renderers). But then how would we define the target?
In V8, the target component is provided in the constructor. We could do the same and then when attaching the target component we would inject the context-menu between it and its parent. But then the target component's parent would be unexpectedly the context-menu instead of the component where the user attached it...
2. Should we provide `setItems()` and `HasValue` API for the component? This is what the V8 version has and also all of the web component demos just use a `<vaadin-list-box>` inside the menu for selecting items. We would need to bring a webjar dependency for list-box.
IMO, regardless if we add this helper API or not, we should keep the option for adding arbitrary components, as it provides support for so many more use-cases.

**Comment by pekam** [comment]
GitHub repository and PR validation build is configured.
The project setup and the first implementation is done in https://github.com/vaadin/vaadin-context-menu-flow/pull/3
but the component still lacks many features.

**Comment by ZheSun88** [comment]
pre-release/snapshot release are ready. discussed with the team. alpha1 release will be performed later, when more people come back from their vacation.

**Comment by pekam** [comment]
`1.0.0.alpha1` released: https://github.com/vaadin/vaadin-context-menu-flow/releases/tag/1.0.0.alpha1
