### ISSUE TITLE
Set open on click in vaadin 14.0.8

### ISSUE THREAD

**Issue by nemanjakmno** [vaadin/vaadin-context-menu-flow#108]
Client type error occurred when contextMenu.setOpenOnClick(true); after upgrading vaadin version to 14.0.8

<img width="612" alt="Screen Shot 2019-10-08 at 15 49 56" src="https://user-images.githubusercontent.com/7590709/66401382-5f771b00-e9e3-11e9-8071-453f085618e7.png">

**Comment by pekam** [comment]
Confirmed, most likely caused by #103.

The reason why our tests didn't catch this: Our integration test page tests this feature by toggling `setOpenOnClick` via button after the first render. The bug reproduces only when `setOpenOnClick` is called on the same roundtrip as the context-menu is created/attached (which is of course the normal use case).

Sorry for this unfortunate regression, we'll fix it asap.
