### ISSUE TITLE
Prototype nested menu support (1d)

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/vaadin-context-menu-flow#31]
Clarify the requirements for the feature using https://github.com/vaadin/vaadin-context-menu/tree/proto-items as the client counterpart

**Comment by pekam** [comment]
Prototype branch: https://github.com/vaadin/vaadin-context-menu-flow/compare/nested-menu-proto

It's implemented by appending the Flow-generated components to a virtual container, and finding those based on their node-ids in the client-side to populate the items-array. If components are later added/removed, everything is moved back to the virtual container in server-side (which keeps track of the children lists) and the items-array is re-created.

The proto uses the `SubMenu` API. There's currently a lot of code duplication, and one challenge is to refactor it as much as possible, with the following problems being present:
- `SubMenu` has all the `HasComponents` API, but cannot implement it, because it would bring the `HasElement` API also
- `GridContextMenu` needs its own definitions for `addItem` also for `SubMenu`
