### ISSUE TITLE
Nested menu support

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/vaadin-context-menu-flow#32]
requires #31

Implement the nested menu feature

**Comment by pekam** [comment]
API proposal:
`MenuItem::getSubMenu()` returns an object for configuring a `SubMenu` starting from that item.
`SubMenu` would have same methods as `ContextMenu` for adding the content:
- Adding items:
  - `MenuItem addItem(String text, ComponentEventListener<ClickEvent<MenuItem>> clickListener)`
  - `MenuItem addItem(Component component, ComponentEventListener<ClickEvent<MenuItem>> clickListener)`
- And the `HasComponents` API:
  - `void add(Component...)`
  - `void remove(Component...)`
  - `void removeAll()`
  - `void addComponentAtIndex(int index, Component component)`
  - `void addComponentAsFirst(Component component)`

The problem is that `SubMenu` cannot really implement `HasComponents`, because it would bring also the `HasElement` and `HasEnabled` APIs, which we don't want to provide for this class.

There's a prototype linked in https://github.com/vaadin/vaadin-context-menu-flow/issues/31

The reason to not have `MenuItem::addItem` method like in V8 is that the Flow `ContextMenu` allows adding any content to the overlay, and inside the items -> `MenuItem::add` cannot be used for adding components to the sub-menu, as it is used for adding children to the item itself -> there's a need for a separate context for the sub-menu.

**Comment by Legioth** [comment]
Would it make sense to introduce `MenuItem::addItem` (or `addSubItem`) as a shorthand for `getSubMenu()::addItem`?

In that way, you could avoid some boilerplate in the typical cases, while still having the possibility to add a Grid inside your nested menu by using `getSubMenu()`.

**Comment by pekam** [comment]
> Would it make sense to introduce `MenuItem::addItem` (or `addSubItem`) as a shorthand for `getSubMenu()::addItem`?

Maybe. The first PR is already bloated so I created a new ticket for this #37
