### ISSUE TITLE
Dynamic grid context menu creation on click time

### ISSUE THREAD

**Issue by stefanuebe** [vaadin/vaadin-context-menu-flow#76]
Currently the grid context menu is build in a static way and cannot be modified depending on the clicked content. This makes it impossible to provide context specific items. 

Request is to provide a listener as there was one in Vaadin 8 to rebuild the menu on each opening time.

(Might be suitable also for non grid context menu).

**Comment by neerup** [comment]
GridContextMenu is also missing the addGridHeaderContextMenuListener() method, where you would build the header contextMenu..

**Comment by mvysny** [comment]
Currently the context menu can be shown eagerly, without having to wait for the server to eventually introduce additional menu items. Having this implemented would require the context menu to work in two modes:

1. Eager mode (if the listener is not specified) - the current implementation.
2. Lazy mode (if the listener is specified - then the menu can only be shown after the listener gathered new set of menu items). This could introduce a slight delay to the menu though.

Perhaps some kind of tag system could be developed instead: certain menu items are only visible on grid items with certain tags. A kind of compromise: it's fast since it can be checked client-side; however the tag system may not be powerful enough for all cases.

Yet, before I start inventing things, let me look at the Vaadin 8 ContextMenu first - it worked okay so perhaps it's easiest to mimick its behavior.

**Comment by mvysny** [comment]
Okay, the Vaadin 8 ContextMenu (which is not even baked in Vaadin 8 but an add-on, here: https://vaadin.com/directory/component/vaadin-contextmenu ) always goes to the server-side before it's displayed, regardless of whether there is a listener specified or not ;)

So I think we can absolutely go ahead with the Lazy mode. So feel free to ignore my "tag" rubbish.

**Comment by gatanaso** [comment]
One possible approach would be to replicate the Vaadin 8 context menu behavior such that when the user clicks, there is a round trip to the server and back, before the menu is displayed. A possible disadvantage of this approach is that it might take some time (depending on the network) before anything is displayed to the user, which might not be the best possible end user experience.

Another approach, as initially suggested by @Legioth is to send the information needed for showing the context menu to the client i.e. through specific `ContextMenu` instances. For this particular case, i.e. showing different context menu for each grid row, it would mean that the server would create such an instance in advance for each row and send it to the client. This approach, however, may potentially be problematic with grids that have 1000s of rows.

**Comment by Legioth** [comment]
> This approach, however, may potentially be problematic with grids that have 1000s of rows.

Grid is lazy loading. The extra data would only need to be sent for rows that are otherwise delivered to the client. It can be discarded when that row is scrolled out from the active area.

**Comment by mvysny** [comment]
The whole functionality can be implemented from purely server-side. The idea is as follows:
1. Add a server-side right-click item listener to a Grid
2. In the listener, create a ContextMenu, populate it with menu items and open it programatically.
3. When ContextMenu is closed, remove all traces of it from DOM.

The following APIs would be required to implement this kind of solution:
1. Add a right-click item listener to the Grid Java API
2. Add `ContextMenu.open(screenX, screenY)` to allow opening ContextMenu programatically
3. It would be good to have some kind of auto-detach of the ContextMenu when it's closed.

**Comment by mvysny** [comment]
> A disadvantage of this approach is that it might take some time (depending on the network) before anything is displayed to the user, which might not be the best possible end user experience.

Sounds like premature optimization. This kind of round-trip is actually always performed by Vaadin 8 ContextMenu.

> specific ContextMenu instances

Pre-populating Grid with potentially hundreds of ContextMenus and sacrificing speed and memory in hopes the user would maybe on one of them, that doesn't sound to me like a good trade-off.

**Comment by sebdavid** [comment]
Hi,
I found the following way to dynamically populate the context menu of the grid, while trying to find a workaround to https://github.com/vaadin/vaadin-grid-flow/issues/366. The code can be copied-pasted in the class SampleCrudView of the bookstore-starter-flow project. Tested with Vaadin 14.0.1 and 13.0.12.

One thing is still missing: a way to cancel the display of the context menu, in the case when no item is selected in the grid for instance. I tried the following :

- Using the method `close()` is not suitable, because in makes the context menu 'blinking' (it is quickly displayed then hidden) ;
- Leaving the context menu empty (no item) ends in the display of a tiny context menu (a ~10px white circle) 

```java
/*grid.asSingleSelect().addValueChangeListener(
                event -> viewLogic.rowSelected(event.getValue()));*/

grid.setSelectionMode(Grid.SelectionMode.MULTI);
GridContextMenu<Product> ctxMenu = grid.addContextMenu();

grid.getElement().addEventListener("vaadin-context-menu-before-open", e->{

    System.out.println("EVENT vaadin-context-menu-before-open");
    Set<Product> items = grid.asMultiSelect().getSelectedItems();
    ctxMenu.removeAll();
    if(items.isEmpty()){
        // ctxMenu.close(); // doing that makes the context menu 'blinking'
        ctxMenu.addItem("Please select an item in the grid");
    }
    else {
        // Dynamically populate the ctx menu
        for(Product p: items){
            ctxMenu.addItem(p.getProductName());
        }
    }
});
```

**Comment by mvysny** [comment]
@sebdavid amazing, thank you for sharing the code! A minor thing: the `vaadin-context-menu-before-open` event seem undocumented (not present in Java API nor HTML API at https://vaadin.com/components/vaadin-context-menu/html-api ); I think we need to add the event to the official API.

**Comment by Legioth** [comment]
Turns out that opening the context menu is already doing a round trip, or in the case of a grid context menu even two round trips. This means that my ideas about how to keep the UX good are quite pointless...
